language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install

script: php vendor/bin/codecept run unit
